travis:
  secure:
    BINSTAR_TOKEN: hB8cB2JyoXMA9lkbsEHQSIs58eUNrLVPBsg0TvXJwUGptJj5bAFds2YXH6P5ditflW51KPcyU3w0YUwvIMFR1KG/OXTf6gFkgYEptyJ2L27ULGcJn3SKxGgPa+IWvgwSDoJaAI7ywoyAc1CflCtLVr8bf0t2XeDLfySzGYgs5OWHOs0U3Z9mxCof+Lhem+UYxI5/tst5+z2DTE3r/HClSmt5ODLbWnEpAl+xCjkK/Qke+xunWZQe2ngUu7Aep32iic1PZRptETzYRpz+ENGqPh/Z9b2tHFTF/QUkjq30we4FtIAXEIQxZ6jGNrfzMSd5u4fwl8lnbldeYwBKQfI8M6KUbqbz7O/txmUd+cNlX99oQqSfpwnI9pMusQtz/zhVNWMwDB0EhO0alM94KauczjLl4mW3JBCRSZSwYfxG6uacIYGxMOg1UG9o7IhhXrm2jguMGFyDCtwASSf+KsGvk24mdN7FEg5QeL+Q8g8HaKp6+LlW/qxZBnOpImVM/ptczG9TRZa4MVlXtHbmADVdPrvTriylZqXwhBUIgU34mJT2d2U7aDCdtNzsssfg0Ot1CKyeGCLGs67LhNmHUL5MEtbDL/VSo2AjapmWjK56pb+80xfAkGHA/vVK6xkeeXWjNexIaa97LyEBgNgqjZnMpSRVrrubPHsHXhFQ3DHBCmM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
