travis:
  secure:
    BINSTAR_TOKEN: TZ11woSwTHcSP7JAZv/I5M7oT5yXcUqrTuep2trRL8bKtxyn1B8UifwzlCFWYo7fm5dnpkfkCw746PtQdUeTfGvxG+NywvKCAkDdYUheqOrOl3NT7AnMNf/EwMu/vBQyiXP+JCwz0ZH7J/ZQBMzP13VMHM819CMC/dlcecC2+YT9hqGvg4UuQwVDWNtR1Nfp8Fg8tc5Aiz+urlad6e/Vsvf84kqCp2QUI3LdC22xewWBOCBrZPQ100dW+n9SddvYBBh+px9H5k3+VJ30mdD4ZzM3+frccgw8Cs6+MHTeZgmIYoNUR4U4gO0rlw8SrhMqdT2Qxr4ZYd1/H/6RjYAmNoRTgH0SxNSpNS2HNh1FdlxrS/mztgUo15aMKJonQ1K3jXxt5R8ZzYh1ETV5jaffP6agQe7f75QpyNRYblkKIJq0uSLWkp0fD2VcsZ/VoqAAyPbFuNjMrcaZZT+37cZEArkZJnvzcnUocRdDeWOuRqBYKynj8CVwxdh3SKP2Ls2aUzQZFp0YXq8p/QaHP6LlFi4Hp5H9HFwvRfBb/+Fktghdi55hMeELLHFvkExbZujveAeiuZgVMq2MzFzCcmT1blCglx5sXqc2HMzmaFs6XS3xqhr/xlkTSDfKEB0Tv4lQ7SbS9HDnkkIZz3KVd0a5q68Qz65mTlMhHZEQHrcZt/I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
